### ISSUE TITLE
AnvilGUI needs bump to newest version

### ISSUE THREAD

**Issue by tuanzisama** [RyseInventory/RyseInventory#59]
**Describe the bug**
The latest version of `RyseInventory` does not work in 1.19.4.
Looks like the `AnvilGUI ` needs to be updated to the latest upstream version

**Screenshots**
<details>
<summary>展开查看</summary>
<pre><code>
java.lang.NoClassDefFoundError: Could not initialize class cn.utoverse.utoverseent.shade.io.github.rysefoxx.inventory.anvilgui.AnvilGUI
	at cn.utoverse.utoverseent.shade.io.github.rysefoxx.inventory.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:581) ~[UtoverseEnt-1.0.0-RELEASE.jar:?]
	at cn.utoverse.utoverseent.playertitle.customize.TitleTagInputGUI.open(TitleTagInputGUI.java:59) ~[UtoverseEnt-1.0.0-RELEASE.jar:?]
	at cn.utoverse.utoverseent.playertitle.customize.TitleCreateGUI.lambda$getTagSelectorItemStack$1(TitleCreateGUI.java:126) ~[UtoverseEnt-1.0.0-RELEASE.jar:?]
	at cn.utoverse.utoverseent.shade.io.github.rysefoxx.inventory.plugin.pagination.InventoryManager$InventoryListener.lambda$onInventoryClick$2(InventoryManager.java:577) ~[UtoverseEnt-1.0.0-RELEASE.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at cn.utoverse.utoverseent.shade.io.github.rysefoxx.inventory.plugin.pagination.InventoryManager$InventoryListener.onInventoryClick(InventoryManager.java:562) ~[UtoverseEnt-1.0.0-RELEASE.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor353.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:git-Pufferfish-67]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3191) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1344) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1321) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1314) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1292) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[pufferfish-1.19.4.jar:git-Pufferfish-67]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
</code></pre>
</details>

**Comment by Rysefoxx** [comment]
Yes AnvilGUI needs to be updated with every Minecraft version as far as I know. If AnvilGUI has already released a version for 1.19.4, I will update that.

**Comment by tuanzisama** [comment]
Thank you for your reply.

AnvilGUI was supported 1.19.4

https://github.com/WesJD/AnvilGUI/issues/250
